apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 4200
    targetPort: http-server
  selector:
    run: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/testing01-221905/testingangular03
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 4200
        env:
        - name: PROJECT_ID
          value: testing01-221905
